### PR TITLE
Add web Next.js stream compress example

### PR DESCRIPTION
**Pull request by myl7**
Related #23

The PR adds a runnable example of Brotli (de)compressing as a reference.
I have manually tested it with large files and ensure the output is as expected.

It can only output correctly together with the fix #25 . The example can also help to verify that fix.

### CODE REVIEW

**Comment by myl7** [comment]
The PR currently has only compression example code.
I will add the decompression part asap since they are very similar.

**Comment by pimterry** [comment]
@socket-security ignore next@*

**Comment by pimterry** [comment]
@myl7 no need to worry about the Socket warnings here - I'm not worried at all about standard dependencies like this for an example app.

**Comment by pimterry** [comment]
In fact, I've just merged this directly for now. You can open a PR to add the decompression part separately, that would be useful but there's no need to make this wait for that.

**Pull request merged**
